project:
  name: "end-to-end-credit-risk-platform"
  target_column: "SeriousDlqin2yrs"
  id_column: "Id"

data:
  raw_path: "data/raw/cs-training.csv"
  processed_path: "data/processed/final_modeling_dataset_v1.csv"
  test_size: 0.2
  random_state: 42

preprocessing:
  knn_imputer_n_neighbors: 5
  outlier_removal: false
  resampling: null

models:
  champion: "catboost"
  threshold: 0.55
  catboost:
    auto_class_weights: "Balanced"
    iterations: 1000
    learning_rate: 0.03
    depth: 6
    random_seed: 42
  xgboost:
    scale_pos_weight: 14.0
    random_state: 42
  lightgbm:
    class_weight: "balanced"
    random_state: 42